2024-02-04 18:50:14,041 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-04 18:50:14,041 - ERROR - view_survey - [L94]- No survey exist, please create a new one.
Traceback (most recent call last):
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 90, in view_survey
    check_question_exist()
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 39, in check_question_exist
    raise Exception("No survey exist, please create a new one.")
Exception: No survey exist, please create a new one.
2024-02-04 18:50:35,369 - INFO - <module> - [L115]- Application starts
2024-02-04 19:01:32,459 - INFO - submit_response - [L69]- Entering submit response
2024-02-04 19:01:32,459 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-04 19:01:32,459 - ERROR - submit_response - [L82]- No survey exist, please create a new one.
Traceback (most recent call last):
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 70, in submit_response
    check_question_exist()
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 39, in check_question_exist
    raise Exception("No survey exist, please create a new one.")
Exception: No survey exist, please create a new one.
2024-02-04 19:01:33,108 - INFO - submit_response - [L69]- Entering submit response
2024-02-04 19:01:33,108 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-04 19:01:33,108 - ERROR - submit_response - [L82]- No survey exist, please create a new one.
Traceback (most recent call last):
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 70, in submit_response
    check_question_exist()
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 39, in check_question_exist
    raise Exception("No survey exist, please create a new one.")
Exception: No survey exist, please create a new one.
2024-02-04 19:01:33,843 - INFO - submit_response - [L69]- Entering submit response
2024-02-04 19:01:33,843 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-04 19:01:33,843 - ERROR - submit_response - [L82]- No survey exist, please create a new one.
Traceback (most recent call last):
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 70, in submit_response
    check_question_exist()
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 39, in check_question_exist
    raise Exception("No survey exist, please create a new one.")
Exception: No survey exist, please create a new one.
2024-02-04 19:01:34,442 - INFO - submit_response - [L69]- Entering submit response
2024-02-04 19:01:34,442 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-04 19:01:34,442 - ERROR - submit_response - [L82]- No survey exist, please create a new one.
Traceback (most recent call last):
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 70, in submit_response
    check_question_exist()
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 39, in check_question_exist
    raise Exception("No survey exist, please create a new one.")
Exception: No survey exist, please create a new one.
2024-02-04 19:01:52,925 - INFO - reset_survey - [L101]- Entering reset survey
2024-02-04 19:01:52,925 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-04 19:01:52,925 - ERROR - reset_survey - [L110]- No survey exist, please create a new one.
Traceback (most recent call last):
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 102, in reset_survey
    check_question_exist()
  File "c:\__MY_WORK\YesOrNoSurvey\main.py", line 39, in check_question_exist
    raise Exception("No survey exist, please create a new one.")
Exception: No survey exist, please create a new one.
2024-02-11 14:38:20,724 - INFO - <module> - [L115]- Application starts
2024-02-11 14:38:20,850 - INFO - <module> - [L115]- Application starts
2024-02-11 14:39:39,826 - INFO - view_survey - [L89]- Entering view_survey
2024-02-11 14:39:39,827 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:39:39,827 - ERROR - view_survey - [L94]- No survey exist, please create a new one.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 90, in view_survey
    check_question_exist()
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 39, in check_question_exist
    raise Exception("No survey exist, please create a new one.")
Exception: No survey exist, please create a new one.
2024-02-11 14:39:59,558 - INFO - view_survey - [L89]- Entering view_survey
2024-02-11 14:39:59,559 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:39:59,559 - ERROR - view_survey - [L94]- No survey exist, please create a new one.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 90, in view_survey
    check_question_exist()
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 39, in check_question_exist
    raise Exception("No survey exist, please create a new one.")
Exception: No survey exist, please create a new one.
2024-02-11 14:40:08,026 - INFO - view_survey - [L89]- Entering view_survey
2024-02-11 14:40:08,027 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:40:08,027 - ERROR - view_survey - [L94]- No survey exist, please create a new one.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 90, in view_survey
    check_question_exist()
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 39, in check_question_exist
    raise Exception("No survey exist, please create a new one.")
Exception: No survey exist, please create a new one.
2024-02-11 14:40:41,657 - INFO - create_question - [L46]- Entering generate question
2024-02-11 14:40:41,662 - ERROR - create_question - [L61]- 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 47, in create_question
    question = request.form["question"]
               ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2024-02-11 14:42:46,055 - INFO - create_question - [L46]- Entering generate question
2024-02-11 14:42:46,058 - INFO - create_question - [L53]- Are you a voter of India?

2024-02-11 14:42:46,058 - INFO - create_question - [L54]- Exiting generate question
2024-02-11 14:43:09,199 - INFO - create_question - [L46]- Entering generate question
2024-02-11 14:43:27,279 - INFO - view_survey - [L89]- Entering view_survey
2024-02-11 14:43:27,279 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:43:27,279 - INFO - view_survey - [L91]- Exiting generate question
2024-02-11 14:44:07,285 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:44:07,286 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:44:07,286 - ERROR - submit_response - [L82]- 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 71, in submit_response
    yes = request.json["yes"]
          ^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 548, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 591, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/flask/wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 631, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-02-11 14:45:13,306 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:45:13,307 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:45:13,308 - ERROR - submit_response - [L82]- 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 71, in submit_response
    yes = request.json["yes"]
          ^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 548, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 591, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/flask/wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 631, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-02-11 14:45:19,047 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:45:19,048 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:45:19,048 - ERROR - submit_response - [L82]- 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 71, in submit_response
    yes = request.json["yes"]
          ^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 548, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 591, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/flask/wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 631, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-02-11 14:45:24,812 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:45:24,812 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:45:24,812 - ERROR - submit_response - [L82]- 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 71, in submit_response
    yes = request.json["yes"]
          ^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 548, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 591, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/flask/wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 631, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-02-11 14:45:33,530 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:45:33,530 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:45:33,530 - ERROR - submit_response - [L82]- 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 71, in submit_response
    yes = request.json["yes"]
          ^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 548, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 591, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/flask/wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 631, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-02-11 14:45:53,617 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:45:53,618 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:45:53,618 - ERROR - submit_response - [L82]- 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 71, in submit_response
    yes = request.json["yes"]
          ^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 548, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 591, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/flask/wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 631, in on_json_loading_failed
    raise BadRequest(
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-02-11 14:46:59,826 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:46:59,827 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:46:59,827 - ERROR - submit_response - [L82]- 400 Bad Request: Failed to decode JSON object: Expecting value: line 2 column 10 (char 11)
Traceback (most recent call last):
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 598, in get_json
    rv = self.json_module.loads(data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/flask/json/provider.py", line 255, in loads
    return json.loads(s, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 10 (char 11)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 71, in submit_response
    yes = request.json["yes"]
          ^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 548, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 607, in get_json
    rv = self.on_json_loading_failed(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/flask/wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 629, in on_json_loading_failed
    raise BadRequest(f"Failed to decode JSON object: {e}")
werkzeug.exceptions.BadRequest: 400 Bad Request: Failed to decode JSON object: Expecting value: line 2 column 10 (char 11)
2024-02-11 14:47:22,917 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:47:22,918 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:47:22,918 - INFO - submit_response - [L75]- Exiting generate question
2024-02-11 14:47:36,114 - INFO - view_survey - [L89]- Entering view_survey
2024-02-11 14:47:36,115 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:47:36,115 - INFO - view_survey - [L91]- Exiting generate question
2024-02-11 14:48:08,769 - INFO - reset_survey - [L101]- Entering reset survey
2024-02-11 14:48:08,770 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:48:08,770 - INFO - reset_survey - [L105]- Exiting reset survey
2024-02-11 14:48:41,178 - INFO - create_question - [L46]- Entering generate question
2024-02-11 14:48:41,179 - ERROR - create_question - [L61]- 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/Users/sourabhkumar/Flask/Project_2_git/yes_no_survey/main.py", line 47, in create_question
    question = request.form["question"]
               ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Volumes/Knox/installation_softwares/anaconda3/lib/python3.11/site-packages/werkzeug/datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2024-02-11 14:49:23,105 - INFO - create_question - [L46]- Entering generate question
2024-02-11 14:49:23,107 - INFO - create_question - [L53]- Do you have a valid driving licence?
2024-02-11 14:49:23,107 - INFO - create_question - [L54]- Exiting generate question
2024-02-11 14:49:56,153 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:49:56,154 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:49:56,154 - INFO - submit_response - [L75]- Exiting generate question
2024-02-11 14:50:01,272 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:50:01,273 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:50:01,273 - INFO - submit_response - [L75]- Exiting generate question
2024-02-11 14:50:02,410 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:50:02,410 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:50:02,410 - INFO - submit_response - [L75]- Exiting generate question
2024-02-11 14:50:09,250 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:50:09,250 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:50:09,250 - INFO - submit_response - [L75]- Exiting generate question
2024-02-11 14:50:09,679 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:50:09,680 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:50:09,680 - INFO - submit_response - [L75]- Exiting generate question
2024-02-11 14:50:10,266 - INFO - submit_response - [L69]- Entering submit response
2024-02-11 14:50:10,267 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:50:10,267 - INFO - submit_response - [L75]- Exiting generate question
2024-02-11 14:50:26,634 - INFO - view_survey - [L89]- Entering view_survey
2024-02-11 14:50:26,635 - INFO - check_question_exist - [L37]- Checking question exist in DB
2024-02-11 14:50:26,635 - INFO - view_survey - [L91]- Exiting generate question
